# Generated by Django 4.2.18 on 2025-01-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climograma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climogramadata',
            name='nome_local',
            field=models.JSONField(default='Local desconhecido'),
            preserve_default=False,
        ),
    ]
