# Generated by Django 4.2.18 on 2025-01-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climograma', '0002_climogramadata_nome_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climogramadata',
            name='nome_local',
            field=models.CharField(default='Local desconhecido', max_length=100),
        ),
    ]
