# Generated by Django 4.2.18 on 2025-01-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climograma', '0003_alter_climogramadata_nome_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climogramadata',
            name='precipitacao_mensal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='climogramadata',
            name='temperatura_mensal',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
