# Generated by Django 4.2.18 on 2025-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climograma', '0004_alter_climogramadata_precipitacao_mensal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climogramadata',
            name='nome_user',
            field=models.CharField(default='Seu Nome', max_length=100),
        ),
    ]
