# Generated by Django 4.2.18 on 2025-01-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climograma', '0005_climogramadata_nome_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='climogramadata',
            name='periodo_escolha',
            field=models.IntegerField(choices=[(1, 'Anual'), (2, 'Mensal'), (3, 'Semanal')], default=2),
        ),
        migrations.AddField(
            model_name='climogramadata',
            name='precipitacao_anual',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climogramadata',
            name='precipitacao_semanal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climogramadata',
            name='temperatura_anual',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climogramadata',
            name='temperatura_semanal',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
